name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.18rc1-alpine
    steps:
    - uses: actions/checkout@v2

#     - name: Set up Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: go1.18

    - name: Build
      run: GOOS=linux CGO_ENABLED=0 go build -v ./...

    - name: Test
      run: GOOS=linux CGO_ENABLED=0 go test -v ./...
